{
  imports = [
    # this is the hardware-configuration.nix generated by cherry
    # todo: strip and move into modules where possible
    ./old-hardware.nix
  ];

  # allow cross compilation to aarch64
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  salad = {
    stateVersion = "24.11";

    displays = [
      {
        # todo: update once deployed to real machine
        name = "Virtual-1";
        width = 1920;
        height = 1080;
        refreshRate = 60;
      }
    ];

    profiles = {
      graphical = true;
    };
  };
}
