name: book

on:
  push:
    paths:
      - "book/**"
  workflow_dispatch:

jobs:
  build:
    name: build book
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: install mdbook
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook

      - name: install mdbook-alerts
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-alerts

      - name: build book
        run: cd book && mdbook build

      - name: upload book artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/book/

  deploy:
    name: deploy book
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
