name: documentation

on:
  push:
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    name: build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install mdbook
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook

      - name: Install mdbook-alerts
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-alerts

      - name: Build book
        run: cd docs && mdbook build

      - name: Upload book artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/book/

  deploy:
    name: deploy documentation
    runs-on: ubuntu-latest

    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
